name: cascade_pipeline
params:
  cascade_num: 3

backbone:
  name: squeezenet1_1
  params:
    pretrained: True

neck: 
  name: fully_conv_neck
  params:
    input_channels: 512
    output_channels: 64

head:
  name: average_pooling_head
  params:
    input_channels: 64