exp_name: FC4

dataset:
  name: CCD
  params:
    data_dir: '/dataset/colorconstancy/quick_data/'
    fold_idx: 0
    input_size: 512
    statistic_mode: False

model:
  backbone:
    name: squeezenet1_1
    params:
      pretrained: True

  neck: 
    name: fully_conv_neck
    params:
      input_channels: 512
      output_channels: 64

  head:
    name: average_pooling_head
    params:
      input_channels: 64
      output_channels: 3
      

  pipeline:
    name: base_pipeline

  loss:
    name: angular_loss
    params: {}

strategy:
  name: base_strategy
  params:
    train_epochs: 200
    eval_every: 1
    ckpt_every: 1
    
  
optimizer:
  lr: 1e-5



