exp_name: FC4
mode: train

dataset:
  name: CCD
  params:
    data_dir: '/mnt/e/colorconstancy/quick_data/'
    fold_idx: 0
    input_size: 512
    aug_num: 4
    statistic_mode: False
  train_loader:
    batch_size: 4
    num_workers: 4
    shuffle: True
    prefetch_factor: 10
    persistent_workers: False
  eval_loader:
    batch_size: 1
    num_workers: 2
    shuffle: False
    drop_last: False
    
model:
  name: base_pipeline
  params:
    pretrained: 'path'

  backbone:
    name: squeezenet1_1
    params:
      pretrained: True

  neck: 
    name: fully_conv_neck
    params:
      input_channels: 512
      output_channels: 64

  head:
    name: average_pooling_head
    params:
      input_channels: 64

criterion:
  name: angular_loss
  params: {}

plugin:
  logger:
    name: 
      - tqdm_logger
      - tensorboard_logger
    params: 
      - {}
      - tb_log_dir: "./log/tb_log/"
        folder_name: ${exp_name}1

  metric:
    name: 
      - loss_metrics
      - timing_metrics
      - best_recorder_metrics
    params: 
      - iteration: True
        epoch: True
        whole: True
        eval: True
      - iteration: True
        epoch: True
        whole: True
        eval: True
      - sort_: min

strategy:
  name: classic_stragtegy
  params:
    exp_name: ${exp_name}
    ckpt_path: './ckpt/'
    train_epochs: 3000
    print_every: 20
    eval_every: 3
    ckpt_every: 50
    device: cuda:0
    device_mode: False
    statis_mode: ${dataset.params.statistic_mode}

  
optimizer:
  name: Adam
  params:
    lr: 3e-4
    weight_decay: 5e-5

lr_scheduler:
  name: CosineAnnealingLR
  params:
    verbose: True
    T_max: 20
    eta_min: 3e-6