exp_name: SIIE
mode: train

dataset:
  name: CCD
  params:
    data_dir: '/dataset/colorconstancy/quick_data/'
    fold_idx: 0
    input_size: 512
    aug_num: 1
    statistic_mode: False
  train_loader:
    batch_size: 16
    num_workers: 8
    shuffle: True
    prefetch_factor: 20
    persistent_workers: True
  eval_loader:
    batch_size: 1
    num_workers: 2
    shuffle: False
    drop_last: False
    
model:
  name: siie_pipeline
  params:
    pretrained: 'path'

  backbone:
    name: three_layer_cnn
    params: {}

  neck: 
    name: identity_neck
    params: {}

  head:
    name: basic_pred_head
    params:
      input_channels: 512
      kernel_size: 13

criterion:
  name: angular_loss
  params: {}

plugin:
  logger:
    name: 
      - text_logger
    params: 
      - {}

  metric:
    name: 
      - loss_metrics
      - timing_metrics
    params: 
      - iteration: True
        epoch: True
        whole: True
        eval: True
      - iteration: True
        epoch: True
        whole: True
        eval: True

strategy:
  name: classic_stragtegy
  params:
    train_epochs: 3000
    iterations_interval: 10
    eval_every: 1
    ckpt_every: 1
    device: cuda:0
    device_mode: False
    statis_mode: ${dataset.params.statistic_mode}

  
optimizer:
  lr: 3e-4



