name: CCD
params:
  data_dir: '/mnt/e/colorconstancy/quick_data/'
  fold_idx: 0
  input_size: 512
  aug_num: 2
  statistic_mode: False
train_loader:
  batch_size: 8
  num_workers: 4
  shuffle: True
  prefetch_factor: 10
  persistent_workers: False
eval_loader:
  batch_size: 1
  num_workers: 2
  shuffle: False
  drop_last: False